### PR TITLE
Lots of cleanups

### PR DESCRIPTION
**Pull request by dsvensson**
Been working on removing the nasty hacks. Not sure how you want this to work. If I should just push to your master with whatever I see fit, or I should create PRs every now and then.

Rust Embedded Newsletter wants to feature this crate, and it should be added to the awesome-rust-embedded list. I feel that there is a bit more work to do even if it works really well for my use case already.

See setup here:
https://github.com/dsvensson/sparsnas-rs/blob/master/src/main.rs#L20

Next up I intend to file a ton of issues in your project detailing what I have in my mental TODO-list so that there is a way forward if the Newsletter picks up some additional contributer(s).

### CODE REVIEW

**Comment by fmckeogh** [comment]
Wow, thats really great! You're contributing so much more than I am, it should really be your project. I can transfer ownership on Crates.io, would you be able to edit Cargo.toml to make you the author and start pushing from your repo?

Thanks :)

**Comment by dsvensson** [comment]
Sure, that works fine by me. Please join in when you get more time :)

**Comment by dsvensson** [comment]
Can we also reparent it so my repo is not a fork of yours, or I'll just delete my repo, create a new one, and push to it?

**Comment by fmckeogh** [comment]
I tried to change the repo owner, but it wasn’t happy because of the name conflict. If you rename your current repo something else I can transfer ownership of this one. :)

**Comment by dsvensson** [comment]
done

**Comment by fmckeogh** [comment]
I’m really sorry, now I’m getting this issue :/

357cfc00-8d95-4864-a7e2-0c7afda63fe3

**Comment by dsvensson** [comment]
ill delete my repo then :)

**Comment by dsvensson** [comment]
deleted

**Comment by dsvensson** [comment]
thanks!

**Comment by fmckeogh** [comment]
No problem! :)

**Comment by dsvensson** [comment]
@chocol4te Have to update crates.io as well

**Comment by fmckeogh** [comment]
Did you not get the owner invite? May I ask what your crates.io username is? I'd ask to delete it but apparently they really don't like deleting crates. :/

**Comment by dsvensson** [comment]
@chocol4te Stupid me. It was indeed in the invitations list. Accepted now. Thanks.

**Pull request merged**
