### PR TITLE
add cc1101::lowlevel::write_register_burst()

### PR DESCRIPTION
**Pull request by SebKuzminsky**
This is useful e.g. for writing PATABLE.

### CODE REVIEW

**Comment by SebKuzminsky** [comment]
Or maybe the PATABLE register should move from Command to Status so it gets the Burst bit automatically from `waddr()`?

**Comment by dsvensson** [comment]
Perhaps some script could massage this PDF to code, backed by a macro to make it less verbose, and output would be a few different variations instead, which in the end are compiled away to just writing a [u8]? The value domain of [u8] is very large, and most permutations are not productive?

https://www.ti.com/lit/an/swra151a/swra151a.pdf

**Comment by Sympatron** [comment]
[915MHz.csv](https://github.com/dsvensson/cc1101/files/13704639/915MHz.csv)
[868MHz.csv](https://github.com/dsvensson/cc1101/files/13704640/868MHz.csv)
[433MHz.csv](https://github.com/dsvensson/cc1101/files/13704641/433MHz.csv)
[315MHz.csv](https://github.com/dsvensson/cc1101/files/13704642/315MHz.csv)

Disclaimer: I did not fully check these values.

**Comment by dsvensson** [comment]
Could also have those CSV files checked in, and a build.rs that generates data types that encapsulates that const data.

**Comment by dsvensson** [comment]
closed due to stale with conflicts

**Pull request closed without merging**
